### ISSUE TITLE
Crashes due to SSL

### ISSUE THREAD

**Issue by danielcherubini** [pellcorp/plugin.video.netflixbmc#1]
I run my own DNS based tunnel, using SNIproxy.

basically, the crash logs are as follows

I might try and fork your repo and look into this, but I'm wondering perhaps theres something you know of.

`01:03:48 T:6768  NOTICE: -->Python Interpreter Initialized<--
01:03:49 T:6768  NOTICE: URL: https://www.netflix.com/MyList?leid=595&link=seeall
01:03:49 T:6768   ERROR: C:\Users\dan\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
01:03:50 T:6768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.SSLError'>
                                            Error Contents: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
                                            Traceback (most recent call last):
                                              File "C:\Users\dan\AppData\Roaming\Kodi\addons\plugin.video.netflixbmc\default.py", line 1108, in <module>
                                                listVideos(url, type)
                                              File "C:\Users\dan\AppData\Roaming\Kodi\addons\plugin.video.netflixbmc\default.py", line 220, in listVideos
                                                content = load(url)
                                              File "C:\Users\dan\AppData\Roaming\Kodi\addons\plugin.video.netflixbmc\default.py", line 126, in load
                                                r = session.get(url, verify=False).text
                                              File "C:\Users\dan\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 476, in get
                                                return self.request('GET', url, **kwargs)
                                              File "C:\Users\dan\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 464, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "C:\Users\dan\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 576, in send
                                                r = adapter.send(request, **kwargs)
                                              File "C:\Users\dan\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 431, in send
                                                raise SSLError(e, request=request)
                                            SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
                                            -->End of Python script error report<--
01:03:50 T:4808   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.netflixbmc/?mode=listVideos&thumb&type=tv&url=https%3a%2f%2fwww.netflix.com%2fMyList%3fleid%3d595%26link%3dseeall
01:03:50 T:4808   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflixbmc/?mode=listVideos&thumb&type=tv&url=https%3a%2f%2fwww.netflix.com%2fMyList%3fleid%3d595%26link%3dseeall) failed
01:03:50 T:6912  NOTICE: Thread BackgroundLoader start, auto delete: false
01:03:52 T:3396  NOTICE: Previous line repeats 1 times.
01:03:52 T:3396  NOTICE: Thread LanguageInvoker start, auto delete: false
01:03:52 T:3396  NOTICE: -->Python Interpreter Initialized<--`

**Comment by danielcherubini** [comment]
forgot to mention, 

windows 10, 32bit, and 64bit
MacOS 10.10.3 64bit

Probably also any variant of linux.

I think the problem is with the version of python, specifically the requests module..

**Comment by danielcherubini** [comment]
https://github.com/kennethreitz/requests/issues/2022

Looks like there was an issue with SNI

**Comment by pellcorp** [comment]
Are you running the version from my repository: http://pellcorp.com/repo/repository.pellcorp.zip

Version 1.3.15 has quite a bit of work from Corona on the SSL stuff
